create authorization
Chevich123/learn-fe pull request #1
Opened 2022-02-02 15:44 UTC by NikitaFalkon

2022-02-02 16:36 UTC, Martiniks requested changes

2022-02-02 16:36 UTC, Martiniks commented on src/app/login/login.component.html
> +             placeholder="username">
Когда у тэга много атрибутов и надо переносить на следующую строку, то все атрибуты лучше в столбец разместить ( один под одним) чтобы было удобнее/понятнее читать код

2022-02-02 16:36 UTC, Martiniks commented on src/app/login/login.component.html
> +  <div *ngIf="getError().length > 0">
"getError().length > 0 "можно заменить на  getError().length  либо для уверенности !!getError().length
либо сделать отдельный метод который возвращает булен, ты эту комбинацию пару раз используешь в нескольких местах кода
например hasErrors()

2022-02-02 16:36 UTC, Martiniks commented on src/app/login/login.component.html
> +             placeholder="password">
см выше

2022-02-02 17:19 UTC, Chevich123 commented
Description коммита совсем ни о чем не говорит. Надо более мнемонически
Например `login page`

2022-02-02 17:30 UTC, Chevich123 commented on src/app/user/iuser.ts
> +  userId: string | undefined;
Не надо явно указывать undefined. Слишком много писанины
Полный аналог твоей строки равен:
`userID?: string`
Посмотри в остальных местах тоже

2022-02-02 17:35 UTC, Chevich123 commented on src/app/login/login.component.ts
> +  login(data: { username: string; password: string }) {
Ты сюда из теймплейта передаешь IUser класс.. 
А нужен ли он вообще если в компоненте есть переменная this.user где уже лежат username & password?
Надо прийти к какому-то одному виду. Либо мы работаем с двумя переменными username & password либо с сущностью класса IUser

2022-02-03 18:05 UTC, Chevich123 requested changes

2022-02-03 18:05 UTC, Chevich123 commented on src/app/app.component.ts
> +  styleUrls: ['./app.component.css']
Упс.. А почему css? Надо чтоб везде было scss

2022-02-03 18:05 UTC, Chevich123 commented on src/app/service/token.service.ts
> +  constructor() {
Пустые конструкторы, которые ничего не добавляют через DI и ничего не делают можно удалять. Они не явнялются строго необходимыми

2022-02-03 18:09 UTC, Chevich123 requested changes
Смотри оставшиеся комменты

2022-02-03 19:05 UTC, Martiniks commented on src/app/login/login.component.ts
> +      }
Старайся использовать имена переменных которые отображают суть. В данном случае ты ожидаешь что придет Token, значит можно назвать не _x_  а _token_.   Однобуквенные переменные используются в основном в циклах и тестовых логах.

2022-02-03 19:06 UTC, Martiniks approved these changes

2022-02-03 19:44 UTC, Chevich123 approved these changes

2022-02-04 07:48 UTC, merged