Feature/login
Chevich123/learn-fe pull request #1
Opened 2023-06-30 10:29 UTC by Bleckfi

2023-06-30 10:32 UTC, Bleckfi commented
вроде все сделал)

2023-06-30 11:53 UTC, jeka0 commented on src/app/app.module.ts
> +    FormsModule,
Ты нигде не используешь модуль FormsModule, поэтому его можно убрать

2023-06-30 11:53 UTC, jeka0 commented on src/app/pages/login/login.component.html
> +        <button>Sign in</button>
Было бы неплохо если бы при неправильном вводе не только выводилась ошибка, но и блокировалась отправка данных на сервер. Например: <button [disabled]="form.invalid">Sign in</button>

2023-06-30 12:02 UTC, scriptSQD requested changes

2023-06-30 12:02 UTC, scriptSQD commented on angular.json
> +    "analytics": "a09dad24-1722-420e-817b-a7c78673de66"
Это можно удалить, консоль во время работы с CLI собирает аналитику и отправляет ее гуглу, но это можно запретить, а ты случайно разрешил.

2023-06-30 12:02 UTC, scriptSQD commented on src/app/pages/login/login.component.html
> +<section>
Мы подключили к нашему проекту Angular Material, лучше использовать готовые компоненты типа mat-form-field, mat-label и директиву matInput, вместо ручной стилизации.

2023-06-30 12:02 UTC, scriptSQD commented on src/app/pages/login/login.component.ts
> +    pass: new FormControl<string>('', [
А здесь ты забыл про имэйл, пароль ты через реактивные формы соберёшь, а вот почту нет

2023-06-30 13:39 UTC, Chevich123 requested changes

2023-06-30 13:39 UTC, Chevich123 commented on src/app/app.component.scss
> +  height: 50px;
Когда пикселей становится много - начинают размеры указывать в rem
Почитай про rem и постарайся их использовать
width, height, font-size обычно в rem если это не попиксельные подвижки
margin, padding может быть и в rem и в px

2023-06-30 13:39 UTC, Chevich123 commented on src/app/pages/login/login.component.ts
> +  get pass() {
А зачем нам этот геттер?

2023-06-30 13:39 UTC, Chevich123 commented on src/app/pages/login/login.component.ts
> +    pass: new FormControl<string>('', [
И инпут надо подключить будет к полю email

2023-07-01 06:08 UTC, scriptSQD requested changes

2023-07-01 06:08 UTC, scriptSQD commented on src/app/pages/login/login.component.html
> +  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@40,300,0,0"
Два раза повторять линк не стоит, и его надо загрузить в index.html. Мы по всему проекту будем использовать эти иконки, а из твоего компонента другим они будут недоступны из-за инкапсуляции.

2023-07-01 06:08 UTC, scriptSQD commented on src/app/pages/login/login.component.ts
> +  email = new FormControl('', [Validators.required, Validators.email]);
Это можно было оставить в форм-группе, но ладно

2023-07-02 10:09 UTC, scriptSQD approved these changes

2023-07-02 14:48 UTC, Chevich123 approved these changes
Мне нравится

2023-07-02 14:48 UTC, Chevich123 commented on src/app/pages/login/login.component.ts
> +  date: FormGroup = new FormGroup({
Мне кажется с форм-билдером было бы интереснее.. Но это тоже норм.

```  
  date = this.fb.group({
    password: ['', [Validators.required, Validators.minLength(6)]],
    email: ['', [Validators.required, Validators.email]],
  });

  constructor(private fb: FormBuilder) {
  }
```

2023-07-02 14:48 UTC, Chevich123 commented on src/app/pages/login/login.component.ts
> +    return console.log(this.date.value);
return тут явно лишний

2023-07-02 17:30 UTC, Bleckfi commented on src/app/pages/login/login.component.ts
> +    return console.log(this.date.value);
Это тоже как тест был

2023-07-02 17:40 UTC, merged