Feature/ greetings
Chevich123/learn-fe pull request #10
Opened 2023-07-13 15:46 UTC by DmitryChevich

2023-07-13 16:38 UTC, jeka0 requested changes

2023-07-13 16:38 UTC, jeka0 commented on src/app/wrapper/wrapper.component.html
> +  <mat-label class="welcome">Welcome, {{ username }}!</mat-label>
Надпись лучше скрыть, когда пользователь не авторизован

2023-07-13 16:38 UTC, jeka0 commented on src/app/wrapper/wrapper.component.html
> +    <button (click)="logout()" *ngIf="!loginVisible()" routerLink="/login">
Эта кнопка появляется на экране логина, даже если пользователь не авторизован

2023-07-13 16:38 UTC, jeka0 commented on src/app/pages/login/login.component.ts
> +  constructor(private authService: AuthService, private router: Router) {}
Router тут нигде не используется

2023-07-13 16:38 UTC, jeka0 commented on src/app/auth.service.ts
> +    this.username = localStorage.getItem('username');
Думаю, лучше тут не сохранять имя пользователя, а при загрузке отправлять запрос на сервер. Если отправить get запрос на http://localhost:3000/profile, то тебе вернется информация о текущем пользователе основываясь на  токене.

2023-07-13 16:47 UTC, jeka0 requested changes

2023-07-13 16:47 UTC, jeka0 commented on src/app/auth.service.ts
> +          this.router.navigate(['/']);
Навигацию лучше перенести в login.component

2023-07-13 17:17 UTC, Chevich123 requested changes

2023-07-13 17:17 UTC, Chevich123 commented on src/app/auth.service.ts
> +    this.username = localStorage.getItem('username');
Давайте получение профиля сделаем отдельным тикетом. Тут надо будет знания rxjs-a

2023-07-13 17:17 UTC, Chevich123 commented on src/app/auth.service.ts
> +          this.router.navigate(['/']);
Навигация в сервисах тоже норм. Нет в принципе тут никаких правил.. Гварды, интерцепторы, сервисы тоже могут навигировать

2023-07-14 10:10 UTC, jeka0 requested changes

2023-07-14 10:10 UTC, jeka0 commented on src/app/wrapper/wrapper.component.ts
> +    return true;
Лучше заменить на return !this.auth.username;. Так намного красивее будет.

2023-07-14 10:55 UTC, Chevich123 requested changes
+ Кнопка логина убегает на центр экрана
+ Рибейс сделан не красиво или не сделан

2023-07-14 10:55 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.ts
> +    return true;
Классическая ошибка джуна

2023-07-16 16:39 UTC, scriptSQD requested changes

2023-07-16 16:39 UTC, scriptSQD commented on src/app/auth.service.ts
> +    localStorage.clear();
Вот это не супер решение, пока мы храним в локалке только токен, но в теории там могуть быть пользовательские настройки (например выбор темная/светлая тема, какие-то стэйты страничек, корзина и т.д.) и другие данные, которые логаут тоже убъет, хотя не должен.

2023-07-16 16:39 UTC, scriptSQD commented on src/app/auth.service.ts
> +          this.router.navigate(['/']);
и все-таки это лучше перенести за пределы сервисного метода логин, потому что могут быть такие ситуации, когда нам, например, надо сделать логин с ридеректом, мы все равно будем обращаться к authService, и тогда мы просто 2 раза будем кидать пользователя, сначала на "/", а потом туда, куда должны редиректить на самом деле

2023-07-16 16:39 UTC, scriptSQD commented on src/app/wrapper/wrapper.component.html
> +    <button (click)="logout()" *ngIf="!loginVisible()" routerLink="/login">
да, тут скорее надо добавить а authService стэйт переменную isAuth$, которая будет каким-то потоком данных (типа сабджекта), и проверять, есть ли авторизация, и только тогда отображать логаут

2023-07-17 08:35 UTC, Chevich123 requested changes

2023-07-17 08:35 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.html
> +    <button (click)="logout()" *ngIf="!loginVisible()" routerLink="/login">
Давайте пока исходить что наши студенты еще не совсем понимают rxjs. Пока рановато городить сабджекты

2023-07-17 14:46 UTC, jeka0 requested changes

2023-07-17 14:46 UTC, jeka0 commented on src/app/wrapper/wrapper.component.ts
> +    return false;
Имелось в виду заменить всю конструкцию if (!this.auth.username) { return true;} return false; на return !this.auth.username;. Оно будет работать точно также, но по коду меньше и в целом выглядит красивее.

2023-07-17 17:25 UTC, scriptSQD requested changes
все тут нормально, но ребэйс не сделан, в истории бардак

2023-07-18 16:05 UTC, jeka0 approved these changes

2023-07-18 16:14 UTC, scriptSQD approved these changes

2023-07-18 19:00 UTC, Chevich123 approved these changes

2023-07-18 19:02 UTC, merged