Feature/add users
Chevich123/learn-fe pull request #11
Opened 2023-07-15 14:14 UTC by Bleckfi

2023-07-16 09:26 UTC, scriptSQD requested changes
С модалкамм намудрил, лучше сделать обычной отдельной страничкой, у тебя почти все готово, нужно только почистить модал сервисы и обычную кнопку (не FAB) с роутер линком на твою страницу users/add

2023-07-16 09:26 UTC, scriptSQD commented on src/app/pages/users/add-user/add-user.component.ts
> +      [Validators.minLength(7), Validators.maxLength(7), this.isNumber],
это не совсем правильный валидатор, тебе стоит поискать regex валидатор для телефона, потому что обычно это строка вида +1 23 1234567

2023-07-16 09:26 UTC, scriptSQD commented on src/app/pages/users/add-user/add-user.component.ts
> +  userForm: FormGroup = this.formBuilder.group({
сюда еще стоило бы добавить password, его всё-таки надо создавать для каждого юзера

2023-07-16 09:26 UTC, scriptSQD commented on src/app/pages/users/add-user/add-user.component.ts
> +        userId: '',
userId можно вообще не передавать, его базы данных генерят автоматически

2023-07-16 11:01 UTC, jeka0 requested changes
Из-за того, что нет перехода на новую страницу, после добавления пользователя список не обновляется.

2023-07-16 11:01 UTC, jeka0 commented on src/app/pages/users/add-user/add-user.component.html
> +        !userForm.controls['name'].hasError('required')
Ошибки бы разделить и указать более конкретное предупреждение, а то не понятно что от тебя ожидается при вводе

2023-07-16 16:19 UTC, Bleckfi commented on src/app/pages/users/add-user/add-user.component.ts
> +        userId: '',
он генерится, но тк это идет от интерфейся, я не могу пропустить это поле, поэтому оставил пустым

2023-07-16 16:23 UTC, scriptSQD commented on src/app/pages/users/add-user/add-user.component.ts
> +        userId: '',
> он генерится, но тк это идет от интерфейся, я не могу пропустить это поле, поэтому оставил пустым

для этого у тайпскрипта есть utility-types, из них тебе нужен Omit, это будет выглядеть так: Omit<IUser, "userId"> (почитать про синтаксис и аргументы для этого дженерика можешь в инете), а результатом будет полная копия интерфейся IUser, но без поля userId

2023-07-16 20:26 UTC, scriptSQD requested changes

2023-07-16 20:26 UTC, scriptSQD commented on src/app/app-routing.module.ts
> +      { path: 'user/add', component: AddUserComponent },
Этого делать не надо было, users/add - норм, тем более, что аы должны были прочитать про children свойство у роутов, и через children сделать добавление, изменение и т.д.

2023-07-16 20:26 UTC, scriptSQD commented on src/app/pages/users/add-user/add-user.component.html
> +      userForm.controls['name'].invalid || userForm.controls['password'].invalid
здесь надо оставить userForm.invalid, это короче и результат такой же

2023-07-16 20:26 UTC, scriptSQD commented on src/app/pages/users/users.component.html
> +<a mat-button color="primary" routerLink="/home">Home</a>
Хоум здесь не нужен,он у нас должен быть в хэдэре на дэшборде

2023-07-16 20:26 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +        console.log(usersResponse.data);
логи убираем

2023-07-17 08:26 UTC, Chevich123 commented on src/app/app-routing.module.ts
> +      { path: 'user/add', component: AddUserComponent },
Очень хорошее замечание

2023-07-17 08:27 UTC, Chevich123 commented on src/app/pages/users/users.component.html
> +<a mat-button color="primary" routerLink="/home">Home</a>
Кстати у нас его пока там нету

2023-07-17 08:27 UTC, Chevich123 requested changes
Надо исправить по комментам

2023-07-17 15:58 UTC, jeka0 approved these changes

2023-07-17 17:40 UTC, scriptSQD requested changes

2023-07-17 17:40 UTC, scriptSQD commented on src/app/pages/users/users.component.html
> +<router-outlet></router-outlet>
этот тут не нужно

2023-07-17 17:40 UTC, scriptSQD commented on src/app/pages/users/add-user/add-user.component.ts
> +    const phoneRegex = /^\+\d\(\d{2}\)\d{3}-\d{2}-\d{2}$/;
а вот регекс этот не пашет.
![image](https://github.com/Chevich123/learn-fe/assets/73490413/6c1136b1-b3a1-4c1a-a7ac-993ed3523936)
надо сделать так, чтобы чисел после плюса было от 1 до 3 (как, например, +1 - для америки, +375 - беларусь, +370 - литва, +49 - германия), для этого после `\d` добавить {1,3}.
А вообще я бы сделал вот такой регекс: `^\+?\d{1,3}\s*\(?\d{2}\)\s*?\d{3}-?\d{2}-?\d{2}$`, вот какие варианты номера он будет мэтчить:
![image](https://github.com/Chevich123/learn-fe/assets/73490413/3998ab4b-18d3-4ad6-bd94-9cae10c17464)

2023-07-17 17:40 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +
это нигде не используется

2023-07-17 17:40 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +  hide = false;
это тоже

2023-07-17 18:49 UTC, scriptSQD approved these changes

2023-07-17 20:11 UTC, Chevich123 approved these changes

2023-07-17 20:25 UTC, merged