delete button
Chevich123/learn-fe pull request #12
Opened 2023-07-18 19:44 UTC by Bleckfi

2023-07-18 20:05 UTC, scriptSQD requested changes

2023-07-18 20:05 UTC, scriptSQD commented on src/app/pages/users/user.service.ts
> +  private url = 'http://localhost:3000/users';
это интересное решение, но его лучше в будущем перепрофилировать под более масштабное - environment interface, но это, наверное, отдельным таском

2023-07-18 20:05 UTC, scriptSQD commented on src/app/pages/users/user.service.ts
>      return this.http.post<IUser>('http://localhost:3000/users', user);
тут забыл свое нововведение в виде this.url

2023-07-18 20:05 UTC, scriptSQD commented on src/app/pages/users/user.service.ts
> +  }
а вот бэк нам на удаление возвращает { result: string; }, а не void

2023-07-18 20:05 UTC, scriptSQD commented on src/app/pages/users/users.component.html
> +      </ng-template>
тут перемудрил, можно убрать индексы и проверки, а после итерации по массиву columns вручную дописать колонку на дэлит:
```html
<ng-container *ngFor="let col of columns">...</ng-container>

<th mat-header-cell>Delete</th>
<td mat-cell>иконка-кпонка на модалку с удалением</td>
```

2023-07-18 20:05 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +    let bool = confirm('Вы уверены что хотите удалить?');
текст лучше на английском писать, в создании юзеров у тебя кстати для ошибки на номер телефона текст тоже был русский. для целостности лучше все писать английским, или уже все русским, но не мешать языки

2023-07-18 20:05 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +    let bool = confirm('Вы уверены что хотите удалить?');
и здесь же кстати, используешь нативный api confirm - это не совсем круто, лучше тут использовать интерактивную модалку от Angular Material. [Вот.](https://material.angular.io/components/dialog/overview)

2023-07-19 13:51 UTC, jeka0 requested changes

2023-07-19 13:51 UTC, jeka0 commented on src/app/pages/users/users.component.html
> +      </ng-template>
у тебя теперь вместо site отображается кнопка удаления

2023-07-19 13:51 UTC, jeka0 commented on src/app/pages/users/users.component.ts
> +    }
как-то много ненужных конструкций. По сути это можно заменить на confirm('Вы уверены что хотите удалить?') && this.userService.delete(userID).subscribe(…);. И это будет работать точно также.

2023-07-19 14:01 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +    }
Мне не нравятся такие "if-стэйтменты", в конце концов производительность удет у обоих решений идентичная, а читаемость кода все равно снижается, я бы оставил конструкцию if, разве что вызов confirm() можно внести в if (confirm())

2023-07-19 14:07 UTC, jeka0 commented on src/app/pages/users/users.component.ts
> +    }
Ну, тут главное убрать ненужные bool и else

2023-07-19 15:24 UTC, jeka0 commented on src/app/pages/users/users.component.ts
> +    let bool = confirm('Вы уверены что хотите удалить?');
У нас, кстати, уже есть готовая модалка (confirm-delete в продуктах). Можно сделать ее не привязанной к продуктам, а передавать туда нужные нам данные и переиспользовать ее уже с пользователями.

2023-07-21 11:32 UTC, jeka0 requested changes

2023-07-21 11:32 UTC, jeka0 commented on src/app/pages/users/users.component.ts
> +    private rout: Router,
Router не используется

2023-07-21 11:32 UTC, jeka0 commented on src/app/pages/users/users.component.ts
>      },
Колонку пароля можно убрать, т.к. мы его не получаем

2023-07-21 11:54 UTC, jeka0 approved these changes

2023-07-21 13:02 UTC, scriptSQD requested changes
Все хорошо, но с темплейтом для колонки удаления опять перемудрил, просто сделай отдельную колонку вручную, после тех, которые ангулар генерирует их *ngFor, без условий и проверок, просто после всех колонок последнюю добавь вручную как два тэга th и td

2023-07-21 13:22 UTC, Bleckfi commented
пытался делать отдельной колонкой, она просто не добавляется, и не знаю почему так, поэтому так получилось

2023-07-21 13:42 UTC, scriptSQD commented
> пытался делать отдельной колонкой, она просто не добавляется, и не знаю почему так, поэтому так получилось

ts:
![image](https://github.com/Chevich123/learn-fe/assets/73490413/f3266dc6-4268-4c17-bed2-f4443a919a1f)
html:
![image](https://github.com/Chevich123/learn-fe/assets/73490413/faecd8f1-9ad4-445a-8fc9-5842d16bb1f6)

я бы сделал так

2023-07-21 13:51 UTC, Bleckfi commented
в точь переписал, не работает

2023-07-21 13:58 UTC, scriptSQD commented
> в точь переписал, не работает

значит что-то не так переписал, может забыл почистить старый код

2023-07-21 14:46 UTC, Bleckfi commented
у тебя работает он?

2023-07-21 14:47 UTC, scriptSQD commented
> у тебя работает он? 

конечно, я сначала проверил, потом скинул

2023-07-22 06:01 UTC, scriptSQD approved these changes

2023-07-22 17:04 UTC, Chevich123 approved these changes

2023-07-22 17:04 UTC, Chevich123 commented on src/app/pages/products/products.component.ts
> +          'Are you really sure you want to delete this product?',
Отличный ход

2023-07-22 17:04 UTC, Chevich123 commented on src/app/pages/users/users.component.ts
> +    const dialogRef = this.dialog.open(ConfirmDeleteComponent, {
Было бы еще неплохо вынести компонет ConfirmDelete из Product куда-нибьудь в папку shared например
Все ж он стал общим , а не только для продуктов

2023-07-22 17:04 UTC, Chevich123 commented on src/app/pages/users/users.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
Subscribe в subscribe как матрёшка - признак не знания rxjs. В данный момент не повод переделывать, но имей в виду, что тут клякса

2023-07-22 17:05 UTC, merged