Save auth
Chevich123/learn-fe pull request #13
Opened 2022-12-01 12:51 UTC by jeka0

2022-12-01 13:06 UTC, scriptSQD requested changes

2022-12-01 13:06 UTC, scriptSQD commented on src/app/shared/services/auth.service.ts
> +const ACCESS_TOKEN = 'access_token';
лучше назвать чем-то вроде "ACCESS_TOKEN_KEY", чтобы были пнеятно, что это ключ локалсторэйджа, в котором хранится токен, а не сам токен

2022-12-01 13:06 UTC, scriptSQD commented on src/app/shared/services/auth.service.ts
> +    this.access_token = window.localStorage.getItem(ACCESS_TOKEN) ?? '';
В ангуларе не надо использовать window, используй localStorage напрямую. А ?? замени на ||

2022-12-01 13:38 UTC, Chevich123 commented
Поддержу комменты Бориса

2022-12-01 13:39 UTC, Chevich123 requested changes
В остальном все норм

2022-12-01 14:37 UTC, scriptSQD approved these changes

2022-12-01 19:02 UTC, Chevich123 approved these changes

2022-12-01 19:11 UTC, HEKTOOTKEH approved these changes

2022-12-02 08:31 UTC, frynn approved these changes

2022-12-02 08:32 UTC, merged