Title added
Chevich123/learn-fe pull request #13
Opened 2023-07-19 11:50 UTC by DmitryChevich

2023-07-19 13:21 UTC, jeka0 approved these changes

2023-07-19 13:27 UTC, Chevich123 requested changes
Надо еще Workshop#3 переделать на ссылку на /

2023-07-19 13:37 UTC, scriptSQD commented
А где же тут titleStrategy?

2023-07-19 13:48 UTC, Chevich123 commented
> А где же тут titleStrategy?

Согласен. Тут кое-чего не хватает :)

2023-07-19 17:31 UTC, Chevich123 requested changes

2023-07-19 17:31 UTC, Chevich123 commented on src/app/app.component.ts
> +import { Router, NavigationEnd, ActivatedRoute } from '@angular/router';
Это похоже неиспользуемые импорты

2023-07-19 17:36 UTC, DmitryChevich commented on src/app/app.component.ts
> +import { Router, NavigationEnd, ActivatedRoute } from '@angular/router';
их удаление не посчитало исправлением, не могу закомитить

2023-07-19 17:56 UTC, Chevich123 approved these changes

2023-07-19 18:35 UTC, jeka0 approved these changes

2023-07-20 07:22 UTC, scriptSQD commented on src/app/app-routing.module.ts
> +      this.title.setTitle(`${title} | Workshop #3`);
но если тайтл будет не указан, то он будет по дефолту браться из head в index.html, этого ли мы хотим? я бы добавил else и пустой тайтл "Workshop #3"

2023-07-20 07:35 UTC, scriptSQD approved these changes

2023-07-20 09:38 UTC, merged