Feature/upload image product
Chevich123/learn-fe pull request #14
Opened 2023-07-20 15:44 UTC by AlexandrYurkevich

2023-07-21 11:12 UTC, jeka0 requested changes

2023-07-21 11:12 UTC, jeka0 commented on src/app/pages/products/add/add.component.ts
> +    this.uploadImage(file);
Зачем нам переменная? Почему бы не напрямую подставить this.uploadImage(event.dataTransfer?.files[0]);

2023-07-21 11:12 UTC, jeka0 commented on src/app/pages/products/add/add.component.ts
> +        console.log(result.filename)
Логи нужно убрать

2023-07-21 11:12 UTC, jeka0 commented on src/app/pages/products/add/add.component.ts
> +    this.uploadImage(file);
Опять переменная

2023-07-21 12:31 UTC, jeka0 approved these changes

2023-07-21 13:34 UTC, scriptSQD requested changes

2023-07-21 13:34 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +      <input type="file" (change)="onFileSelected($event)" accept="image/*" style="display: none" #fileInput>
я думаю здесь onChange ниего делать не надо, если пользователь с первого раза не попадет на нужную картинку, а два раза загрузит разные, то обе окажутся на сервере, хотя одна из них будет неиспользованная, я бы отправлял картинку на сервер вместе со всей формой в методе onSubmit

2023-07-21 13:34 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +      <div class="drop-zone" (dragover)="onDragPrevent($event)" (dragleave)="onDragPrevent($event)" (drop)="onDrop($event)">
dragleave тут по идее ничего не делает, его можно убрать

2023-07-21 14:37 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +      <div class="drop-zone" (dragover)="onDragPrevent($event)" (dragleave)="onDragPrevent($event)" (drop)="onDrop($event)">
создавать для этого дела отдельные функции, кстати, не обязательно. можно прямо в ковычках сделать $event.preventDefault(), если в этом заключается вся логика функии onDragPrevent

2023-07-21 15:28 UTC, AlexandrYurkevich commented on src/app/pages/products/add/add.component.html
> +      <input type="file" (change)="onFileSelected($event)" accept="image/*" style="display: none" #fileInput>
change здесь для того чтобы вызываться после выбора файла, а не при клике.
Ну в форме мы отправляем уже строку картинки, если просто перед формой отправлять отдельным запросом картинку, то нужно будет ещё проверять что она ещё существует.
Не знаю всё ли я понял верно из ревью.

2023-07-21 15:31 UTC, AlexandrYurkevich commented on src/app/pages/products/add/add.component.html
> +      <input type="file" (change)="onFileSelected($event)" accept="image/*" style="display: none" #fileInput>
ну и поидее, если превью на странице добавления надо делать обращаясь к базе, то картинка должна быть загружена раньше отправки формы.

2023-07-21 15:44 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +      <input type="file" (change)="onFileSelected($event)" accept="image/*" style="display: none" #fileInput>
никто не мешает считать каритнку с диска пользователя, ведь она оттуда пришла с самого начала

2023-07-22 17:08 UTC, Chevich123 approved these changes

2023-07-22 17:12 UTC, scriptSQD approved these changes
Я все равно считаю, что логику загрузки картинок надо переделать, но технически тут все правильно

2023-07-23 09:16 UTC, merged