Added users table
Chevich123/learn-fe pull request #15
Opened 2022-12-06 13:38 UTC by frynn

2022-12-06 13:49 UTC, HEKTOOTKEH approved these changes

2022-12-06 13:56 UTC, Chevich123 requested changes

2022-12-06 13:56 UTC, Chevich123 commented on src/app/users/users.component.html
> +<a routerLink="/"><button>Back to Dash</button></a>
Добавь тут пробельную строку

2022-12-06 13:56 UTC, Chevich123 commented on src/app/users/users.component.ts
> +
А тут замного пробельных строк

2022-12-06 13:57 UTC, scriptSQD requested changes

2022-12-07 13:51 UTC, Chevich123 commented
Если кликнуть на закладку Files Changed и посмотреть изменения которые делает ПР то видно что остались места где в конце файла надо добавить побельные строки. Там красный значек висит

2022-12-07 15:04 UTC, Chevich123 approved these changes

2022-12-07 15:05 UTC, scriptSQD approved these changes

2022-12-07 15:05 UTC, merged