Feature/editing products
Chevich123/learn-fe pull request #15
Opened 2023-07-22 18:43 UTC by DmitryChevich

2023-07-23 12:32 UTC, jeka0 requested changes

2023-07-23 12:32 UTC, jeka0 commented on src/app/pages/products/editing/editing.component.html
> +    [disabled]="productForm.invalid"
Лучше бы еще проверять на изменение формы. Если не было изменений, то зачем нам отправлять данные на сервер? Изменение формы можно проверить, используя productForm.dirty

2023-07-23 12:32 UTC, jeka0 commented on src/app/pages/products/editing/editing.component.ts
> +    return control.value === '' || control.value > 0
Так как к нам с сервера все незаполненные поля приходят со значением null, то данная проверка не проходит, если не ввести какое-либо значение

2023-07-23 12:32 UTC, jeka0 commented on src/app/pages/products/products.component.ts
> +    private router: Router,
Router не используется

2023-07-23 12:32 UTC, jeka0 commented on src/app/pages/products/editing/editing.component.ts
> +    }
Так как роута данного компонента определяется по наличию id. Не будет такого случая, что мы окажемся на этой роуте без id.

2023-07-24 09:56 UTC, Chevich123 requested changes

2023-07-24 09:56 UTC, Chevich123 commented on src/app/pages/products/editing/editing.component.ts
> +    if (!this.productForm.dirty) {
Тут ты неверно понял Женю. Надо если не было изменения не зажигать кнопку Submit (disable)
Т.е надо к условию invalid в темплейте на disable кнопки добавить и !dirty

2023-07-24 09:56 UTC, Chevich123 commented on src/app/products.service.ts
> +      'http://localhost:3000/products/' + id,
Строки в ангуларе лучше формировать не сложением а через интерполяцию
```
`http://localhost:3000/products/${id}`
```
Это более наглядно и на самом деле более безопасно

2023-07-24 09:56 UTC, Chevich123 commented on src/app/products.service.ts
> +      'http://localhost:3000/products/' + id,
`http://localhost:3000/products` можно вынести в константы сервиса и просто переиспользовать в каждом вызове
Будет даже боле интересно
```
`${this.url}/&{id}`
```

2023-07-24 09:56 UTC, Chevich123 commented on src/app/pages/products/add/add.component.ts
> +
Что-то ты нахомутал с рибейсом, что в твоем ПР появился код загрузки картинок

2023-07-24 10:25 UTC, DmitryChevich commented on src/app/pages/products/add/add.component.ts
> +
Так он должен быть, загрузка картинок уже приклеена к мейну, поэтому я и делал ребейс

2023-07-24 10:32 UTC, Chevich123 commented on src/app/pages/products/add/add.component.ts
> +
Ну по логике он должен быть в main, а не в твоем ПР-е. 
Ты же не менял ничего в логике загрузки картинок?
В ПР должно быть только то что ты сделал

2023-07-24 12:58 UTC, jeka0 requested changes
Нужно подправить ребейз

2023-07-24 13:23 UTC, scriptSQD requested changes
в целом все нормально, но с историей накосячил, надо сделать хороший ребэйс

2023-07-24 13:23 UTC, scriptSQD commented on src/app/app-routing.module.ts
> +            path: ':id',
лучше сделать edit/:id, обычно /:id используется для того, чтобы открывать страничку с информацией про конкретный продукт по id

2023-07-24 13:23 UTC, scriptSQD commented on src/app/products.service.ts
> +  url = 'http://localhost:3000/products';
тут url лучше сделать private readonly, так можно и оптимизации некоторые задействовать, и уберечь от модификаций со стороны приложения

2023-07-24 13:39 UTC, jeka0 requested changes

2023-07-24 13:39 UTC, jeka0 commented on src/app/pages/products/products.component.ts
> +      error: (err) => console.log(err),
Продублировалось при ребейзе

2023-07-24 15:25 UTC, closed without merging