Creat product
Chevich123/learn-fe pull request #18
Opened 2022-12-09 14:16 UTC by HEKTOOTKEH

Создание нового продукта

2022-12-09 14:33 UTC, Chevich123 requested changes

2022-12-09 14:33 UTC, Chevich123 commented on src/app/productstable/productstable.component.html
> +  Create new products
Create new product

2022-12-09 14:33 UTC, Chevich123 commented on src/app/shared/services/products.service.ts
> +          localStorage.setItem(ACCESS_TOKEN_KEY, this.access_token);
Хм. А это все тут зачем? Разве мы меняем токен? Мне казалось он у нас постоянный

2022-12-09 14:33 UTC, Chevich123 commented on src/app/createproduct/createproduct.component.ts
> +    this.router.navigateByUrl('products');
Тут получается что навигация произойдет ДО того как запись попытается быть вставленной. Это не хорошо. 
Навигация должна быть только если запись успешно вставлена.

В случае ошибки можешь вывести ее текст в виде сообщения, но надо статься в той же форме пока пользователь либо не сможет сохранить запись либо не нажмет отмену

2022-12-09 14:33 UTC, Chevich123 commented on src/app/createproduct/createproduct.component.ts
> +      width: [''],
Тут нужна валидация что это число. Попробуй ввести во все ячейки слово **_тест_** и ты сломаешь сервер :)

2022-12-09 14:33 UTC, Chevich123 commented on src/app/app.module.ts
> +    CreateproductComponent,
Очень некрасиво получаются у нас названия компонентов
Надо бы чтоб было красиво
Сделай CreateProductComponent
имя файла create-product.component.ts
и роуту сделай create-product

По аналогии поменяй и в products-table.component.ts & ProductsTableComponent

2022-12-09 14:34 UTC, Chevich123 requested changes
смотри комменты

2022-12-09 14:59 UTC, Chevich123 commented on src/app/app-routing.module.ts
> +    path: 'createproducts',
И надо подвести создание продукта внутрь враппера

2022-12-09 21:07 UTC, Chevich123 requested changes

2022-12-09 21:07 UTC, Chevich123 commented on src/app/app-routing.module.ts
>        {
И всё-таки ты понял неверно. Надо сюда поместить роуту. Чтоб страничка ВИЗУАЛЬНО была внутри враппера (обёрнутая враппером). И убрать линку из меню. Выход на создание продукта должен быть ТОЛЬКО из странички списка продуктов.

2022-12-10 09:36 UTC, scriptSQD requested changes

2022-12-10 09:36 UTC, scriptSQD commented on src/app/create-product/create-product.component.ts
> +  formGroup: FormGroup;
я бы создал форм группу прямо здесь, а не относил её в констурктор. мы ничего динамического не принимаем, что могло бы поменять значение группы, так что ее можно статически инициализировать вместе с определением

2022-12-10 09:36 UTC, scriptSQD commented on src/app/create-product/create-product.component.ts
> +    });
это тогда надо перенести к определению formGroup, и убрать из конструктора

2022-12-10 09:36 UTC, scriptSQD commented on src/app/shared/services/products.service.ts
> +}
вот это всё тебе совсем не нужно

2022-12-10 09:36 UTC, scriptSQD commented on src/app/shared/services/products.service.ts
> +    this.access_token = localStorage.getItem(ACCESS_TOKEN_KEY) || '';
про аксесс токен вообще забудь, он никакого отношения к продуктам не имеет, его тут быть не должно

2022-12-10 09:36 UTC, scriptSQD commented on src/app/shared/services/products.service.ts
> +  createproduct(payload: IProductPayload): Observable<IProductDTO> {
а тут поменяй типа payload на IProduct, и возвращаемый тип тоже на IProduct

2022-12-10 09:36 UTC, scriptSQD commented on src/app/shared/services/products.service.ts
> +      .post<IProductDTO>(`${environment.apiUrl}/products`, payload)
здесь поменяй возвращаемый тип запроса с IProductDTO на IProduct

2022-12-10 09:36 UTC, scriptSQD commented on src/app/products/products.component.ts
> +  }
это тебе не надо

2022-12-10 09:36 UTC, scriptSQD commented on src/app/products/products.component.html
> +</button>
```suggestion
<a routerLink="/create-product">
<button mat-button class="mat-button" color="custom">
  Create new product
</button>
</a>
```

обрабатывать навигацию через клик ивенты на кнопке... сомнительное решение, когда у нас есть нативные ссылки с поддержкой ангуларовского роутера

2022-12-10 09:36 UTC, scriptSQD commented on src/app/create-product/create-product.component.ts
> +    });
И еще я не уверен, стоит ли нам использовать старый синтаксис нетипизированных форм. В ангуларе 14 версии появились типизированные формы и разработчиков настоятельно просят переходить к типизироанным формам, так что я бы использовал тут `this.fb.control` и устанавливал бы типы контролсов

2022-12-10 10:03 UTC, scriptSQD commented on src/app/create-product/create-product.component.ts
> +}
пустой метод ngOnInit() е обязательно оставлять, его стоит убрать и убрать `implements OnInit` после класса

2022-12-10 10:34 UTC, HEKTOOTKEH commented on src/app/app-routing.module.ts
>        {
Я что-то не могу понять как это сделать, я посмотрел файлы самого врапера, апп-продукт и те в которых он есть, но не понял

2022-12-10 10:43 UTC, scriptSQD commented on src/app/app-routing.module.ts
>        {
@Chevich123 Мне кажется, вы его запутали :) Комментарий вы оставили на роуте products,который уже под враппером, тут всё в порядке.

2022-12-10 10:44 UTC, scriptSQD commented on src/app/app-routing.module.ts
> +    path: 'createproducts',
@HEKTOOTKEH Вот этот объект надо перенесте в массив `children` у `WrapperComponent`

2022-12-10 10:46 UTC, HEKTOOTKEH commented on src/app/create-product/create-product.component.ts
> +}
я его удалял видимо не сохранилось

2022-12-10 10:53 UTC, HEKTOOTKEH commented on src/app/app-routing.module.ts
>        {
Не я так понял что надо сделать место где вводиться данные нового продукта враппер добавить

2022-12-10 15:11 UTC, scriptSQD requested changes
Теперь только по мелочам исправь, а так норм

2022-12-10 15:11 UTC, scriptSQD commented on src/app/products/products.component.html
> +</a>
лучше всего все-таки будет так

```suggestion
<a mat-button class="mat-button" color="custom" routerLink="/create-product">
  Create new product
</a>
```

2022-12-10 15:11 UTC, scriptSQD commented on src/app/shared/services/products.service.ts
> +import { tap } from 'rxjs/operators';
это скорее всего неиспользованный импорт, его можно убрать

2022-12-10 15:12 UTC, scriptSQD commented on src/app/create-product/create-product.component.ts
> +    });
@Chevich123 это вопрос к вам, будем грузить ребят новыми концептами, или пускай будет как есть?

2022-12-10 15:48 UTC, scriptSQD approved these changes

2022-12-10 15:55 UTC, jeka0 approved these changes

2022-12-10 17:21 UTC, frynn approved these changes

2022-12-11 14:59 UTC, Chevich123 approved these changes

2022-12-11 15:00 UTC, merged