product image
Chevich123/learn-fe pull request #19
Opened 2023-07-25 16:15 UTC by Bleckfi

2023-07-26 14:03 UTC, jeka0 requested changes

2023-07-26 14:03 UTC, jeka0 commented on src/app/pages/products/products.component.html
> +            width="130"
Лучше перенести ограничения размеров в стили, также нужно добавить ограничение по высоте, ну и параметр object-fit: contain; чтобы сохранить пропорции изображения

2023-07-26 14:03 UTC, jeka0 commented on src/app/pages/products/products.component.ts
> +            this.productImages[product._id] = safeImageUrl;
Можно подкорректировать интерфейс продукта и добавлять в продукт url его изображения, мне кажется так будет проще

2023-07-26 14:13 UTC, jeka0 requested changes

2023-07-26 14:13 UTC, jeka0 commented on src/app/pages/products/products.component.ts
> +      this.productsService.loadProductImage(product.image).subscribe(
А, еще добавь проверку на отсутствие картинки, а то сейчас идут запросы по undefined и падают ошибки

2023-07-26 14:49 UTC, Chevich123 commented on src/app/pages/products/products.component.ts
> +            this.productImages[product._id] = safeImageUrl;
Это не урл. Это бинартик каринки. Но идея верна - можно расширить интерфейс продукта и добавить туда это.
Я бы назвал лучше imagePreview

2023-07-26 14:51 UTC, Chevich123 requested changes
Мне не нравится работа с fileReader. Туда так и просится Subject
В остальном я согласен с Женей

2023-07-27 12:49 UTC, Chevich123 requested changes

2023-07-27 12:49 UTC, Chevich123 commented on src/app/services/image.service.ts
> +    if (!imageUrl) {
В идеале сюда даже не должно быть захода
Убери undefined в описании imageUrl

2023-07-27 12:49 UTC, Chevich123 commented on src/app/services/products.service.ts
> +  loadProductImage(imageUrl: string | undefined): Observable<Blob> {
А почему в product сервисе еще осталась работка с загрузкой картинок?
Надо все запросы к серверу перенести на работу с ImageService

2023-07-27 13:55 UTC, scriptSQD approved these changes

2023-07-27 15:23 UTC, jeka0 approved these changes

2023-07-27 17:58 UTC, Chevich123 approved these changes

2023-07-27 19:24 UTC, merged