Form to add new users
Chevich123/learn-fe pull request #19
Opened 2022-12-11 16:46 UTC by frynn

2022-12-11 17:54 UTC, Chevich123 requested changes

2022-12-11 17:54 UTC, Chevich123 commented on src/app/app-routing.module.ts
> +          path: 'new',
Правильная роута. Молодец. А вот у Алексея неправильная. И я этого не увидел :(

2022-12-11 17:54 UTC, Chevich123 commented on src/app/app-routing.module.ts
> +          component: NewuserComponent,
Назови пожалуйста NewUserComponent или CreateUserComponent. Так как сейчас нечитаемо.. Больше похоже на немецкий язык

2022-12-11 17:54 UTC, Chevich123 commented on src/app/newuser/newuser.component.ts
> +export class NewuserComponent implements OnInit {
NewUserComponent и файлы все соотрветственно new-user.component.ts
Или CreateUserComponent

2022-12-11 17:54 UTC, Chevich123 commented on src/app/newuser/newuser.component.ts
> +    site: this.fb.control<string | null>(''),
А вот тут у тебя будет веселее.. Надо сделать валидации правильные. Email, Phone & Site
В гугле есть много интересных паттернов для валидации Phone & Site
Для email можно использовать Validators.email

2022-12-11 17:54 UTC, Chevich123 commented on src/app/users/users.component.html
> +<router-outlet></router-outlet>
А это тут зачем? Мы что-то пробрасываем внутрь компонента Users?

2022-12-11 17:54 UTC, Chevich123 commented on src/app/users/users.component.scss
> +}
Тут пробельной строчки похоже не хватает

2022-12-11 17:55 UTC, Chevich123 commented
И еще помести new-user папку внутрь папки users. Посмотри как это сделано с продуктами

2022-12-11 17:56 UTC, Chevich123 commented on src/app/newuser/newuser.component.ts
> +    site: this.fb.control<string | null>(''),
И на пароль можешь накинуть какие-то ограничения. Наприер не менее 8 символов. И еще что душе угодно. Но в пределах разумного

2022-12-11 19:02 UTC, HEKTOOTKEH approved these changes

2022-12-12 10:54 UTC, jeka0 approved these changes

2022-12-12 18:12 UTC, Chevich123 approved these changes

2022-12-12 18:12 UTC, merged