Feature/error handler
Chevich123/learn-fe pull request #21
Opened 2023-07-27 11:02 UTC by AlexandrYurkevich

Я не уверен, что он работает так как надо.

2023-07-27 11:58 UTC, scriptSQD requested changes

2023-07-27 11:58 UTC, scriptSQD commented on src/app/pages/products/add/add.component.ts
> +    this.productsService.createProduct(this.productForm.value).subscribe(() => this.router.navigateByUrl('/products'));
тут для наглядности лучше оставить сигнатуру Observer с { next: () => {...} }

2023-07-27 11:58 UTC, scriptSQD commented on src/app/shared/interceptors/error.interceptor.ts
> +        return throwError(()=> new Error(error.message))
этого тут не понял, можно просто выкинуть `throw Error(...)` и rx сам перекинет эту ошибку на поток error

2023-07-27 11:58 UTC, scriptSQD commented on src/app/wrapper/wrapper.component.html
> +</div>
это вообще не рабочая тема, если ошибок много - мы остаемся без нормального экрана приложения
![image](https://github.com/Chevich123/learn-fe/assets/73490413/b046436e-6d95-41c0-89f8-50bceca65c90)

2023-07-27 12:40 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.html
> +</div>
Можно как вариант сообщения которые уже есть в списке не добавлять

2023-07-27 12:43 UTC, Chevich123 requested changes

2023-07-27 12:43 UTC, Chevich123 commented on src/app/pages/products/add/add.component.ts
> +    this.productsService.createProduct(this.productForm.value).subscribe(() => this.router.navigateByUrl('/products'));
Ну обычно если только next то оставляют только функцию. Без наглядности

2023-07-27 12:43 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.scss
> +}
Судя по css он будет раздвигать экран вниз.. А можно так чтобы это все висело НАД основной информацией и ничего никуда не двигало?

2023-07-27 13:28 UTC, AlexandrYurkevich commented on src/app/shared/interceptors/error.interceptor.ts
> +        return throwError(()=> new Error(error.message))
мне писало мол просто throwError(error) это deprecated, мне глаза мозолят эти перечёркнутые методы.

2023-07-27 13:30 UTC, AlexandrYurkevich commented on src/app/wrapper/wrapper.component.html
> +</div>
я наоборот думаю что дубликаты нужны. По переполнению, могу поставить ограничение на растягиваемость контейнера, чтобы при большом количестве скрол был. Но вообще тут кнопка очистки есть.

2023-07-27 13:32 UTC, AlexandrYurkevich commented on src/app/wrapper/wrapper.component.scss
> +}
Не, там всё ок, просто чтобы кнопка очистки не растягивалась на весь экран, я ngFor и кнопку в отдельный контейнер кинул - <div style="position: absolute; z-index: 3; width: 100%;">

2023-07-27 13:39 UTC, scriptSQD commented on src/app/shared/interceptors/error.interceptor.ts
> +        return throwError(()=> new Error(error.message))
откуда ты взял throwError, зачем тебе rx-овские операторы? просто брось ошибку, как это делается в ts нативно, вместо return - throw Error(...)

2023-07-27 13:49 UTC, jeka0 commented on src/app/wrapper/wrapper.component.html
> +</div>
Вообще, неплохо бы добавить возможность скрыть или открыть список ошибок.

2023-07-27 18:06 UTC, Chevich123 requested changes

2023-07-27 18:06 UTC, Chevich123 commented on src/app/shared/interceptors/error.interceptor.ts
> +        throw Error();
Я тут подумал. Давай сделаем слегка по другому
```
catchError((err: HttpErrorResponse) => {
        ........
        return throwError(() => err);
      }),
```
      
Тогда мы пробросим дальше ошибку которую перехватили. И при желании ее можно будет использовать где-нибудь

2023-07-28 10:13 UTC, jeka0 approved these changes

2023-07-28 15:03 UTC, Chevich123 approved these changes

2023-07-28 15:03 UTC, scriptSQD approved these changes

2023-07-28 15:04 UTC, merged