environment service added
Chevich123/learn-fe pull request #22
Opened 2023-07-27 15:15 UTC by DmitryChevich

2023-07-27 16:25 UTC, scriptSQD approved these changes

2023-07-27 18:10 UTC, Chevich123 requested changes
А остальные сервисы кто поправит? Не должно быть нигде явного упоминания localhost:3000. Только работа с environment.ts
![image](https://github.com/Chevich123/learn-fe/assets/18614201/637361bf-ea26-48dc-8ab0-9c0662d10ea1)

2023-07-27 18:27 UTC, DmitryChevich commented
> А остальные сервисы кто поправит? Не должно быть нигде явного упоминания localhost:3000. Только работа с environment.ts ![image](https://user-images.githubusercontent.com/18614201/256626768-637361bf-ea26-48dc-8ab0-9c0662d10ea1.png)

Из этого списка всё было поправлено, кроме одного, в продукт сервисе и ауф сервисе всё было уже готово

2023-07-27 19:05 UTC, jeka0 approved these changes

2023-07-28 10:11 UTC, scriptSQD commented
Опять поломалась история, надо сделать ребэйс

2023-07-28 10:47 UTC, jeka0 reviewed
Еще в image.service и products.service остались localhost:3000

2023-07-28 18:29 UTC, Chevich123 approved these changes

2023-07-28 18:52 UTC, merged