Added ability to edit user
Chevich123/learn-fe pull request #22
Opened 2022-12-14 15:17 UTC by frynn

2022-12-14 15:31 UTC, jeka0 approved these changes

2022-12-14 15:34 UTC, scriptSQD approved these changes

2022-12-14 16:41 UTC, HEKTOOTKEH approved these changes

2022-12-14 18:26 UTC, Chevich123 approved these changes

2022-12-14 18:35 UTC, Chevich123 commented on src/app/users/edit-user/edit-user.component.ts
> +  users: IUser[] = [];
Непонятно зачем это тут

2022-12-14 18:37 UTC, Chevich123 requested changes
Мелкие нюансы. Давай их поправим

2022-12-14 18:37 UTC, Chevich123 commented on src/app/users/edit-user/edit-user.component.ts
> +  ngOnInit(): void {}
От интициализации тоже можно избавиться. Надо будет еще убрать implemented OnInit

2022-12-14 18:39 UTC, Chevich123 requested changes

2022-12-14 18:39 UTC, Chevich123 commented on src/app/users/edit-user/edit-user.component.html
> +    Edit user
И сделай еще кнопку Cancel с редиректом на табличку пользователей

2022-12-15 08:12 UTC, Chevich123 approved these changes

2022-12-15 08:12 UTC, merged