Editing products
Chevich123/learn-fe pull request #23
Opened 2022-12-14 15:18 UTC by HEKTOOTKEH

добавление продукта (проблема возникает про добавлении this.product.name и т.д. в форму находящуюся в editing-product. Сделано для того что бы человек видел изначальные значения и не переписывал всё заново)

2022-12-14 16:54 UTC, scriptSQD commented
Сразу вижу проблемы с роутингом, ты неправильно сделал параметр id для роуты, и айди из ссылки ты парсишь какими-то обходными путями, для этого у ангулара есть api и там параметр из ссылки можно извлечь более правильным и простым путем

2022-12-14 16:56 UTC, scriptSQD commented
И у тебя не получается установить исходные значения для контролсов потому, что на момент инициализации формГруппы у тебя product еще не имеет значения, потому что ты к тому моменту еще даже не сделал запрос на сервер. Пересмотри процесс инициализации компонента и помести создание формГруппы в констурктор ПОСЛЕ того, как успешно получишь продукт, а если не получишь, то делай редирект обратно на products

2022-12-14 18:31 UTC, Chevich123 approved these changes

2022-12-14 18:33 UTC, Chevich123 commented
Кстати формГруппу можно было создать и ДО того как получишь сам продукт. Создаешь формГруппу со всеми валидациями а уже после того как получил продукт делаешь:
``` this.formGroup.patchValue(product) ```
Те поля из продукта которые были упомянуты в формНруппе присвоятся в формГруппу.
Но так как ты сделал тоже норм

2022-12-14 18:40 UTC, Chevich123 commented on src/app/products/editing-product/editing-product.component.html
> +    </button>
Вот бы еще рядом кнопку Cancel с редиректом на список продуктов

2022-12-15 08:29 UTC, frynn approved these changes

2022-12-15 15:01 UTC, scriptSQD requested changes

2022-12-15 15:01 UTC, scriptSQD commented on src/app/products/products.component.ts
> +    private router: Router,
непонятно, зачем ты опять инжектишь роутер

2022-12-15 15:46 UTC, jeka0 approved these changes

2022-12-15 16:14 UTC, scriptSQD approved these changes

2022-12-15 16:14 UTC, merged