pictures in edit and add screen
Chevich123/learn-fe pull request #23
Opened 2023-07-30 14:46 UTC by AlexandrYurkevich

он там подсвечивает пару строк, но всё работает

2023-07-31 09:04 UTC, scriptSQD requested changes

2023-07-31 09:04 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +      <div class="drop-zone" style="{{preview && 'min-height: fit-content;'}}" (dragover)="$event.preventDefault()" (drop)="onDrop($event)">
это не круто, лучше использовать [ngStyle], а еще лучше - [[ngClass]](https://angular.io/api/common/NgClass#description), который будет тригерить классы в зависимости от результата выражения (true/false)

2023-07-31 09:04 UTC, scriptSQD commented on src/app/pages/products/add/add.component.ts
> +      next: (result) => this.showPreview(result.filename),
subscribe в subscribe, надо бы переделать в rx-way, со свитчМапами

2023-07-31 09:04 UTC, scriptSQD commented on src/app/pages/products/editing/editing.component.html
> +      <div class="drop-zone" style="{{preview && 'min-height: fit-content;'}}" (dragover)="$event.preventDefault()" (drop)="onDrop($event)">
здесь та же история с ngClass, а еще у тебя, похоже, не подключено форматирование кода, потому что prettier большое количество аттрибутов расставляет на новые строки

2023-07-31 09:04 UTC, scriptSQD commented on src/app/pages/products/editing/editing.component.ts
> +      .subscribe((product) => {this.productForm.patchValue(product); product.image && this.showPreview(product.image)});
опять subscribe в subscribe

2023-07-31 09:04 UTC, scriptSQD commented on src/app/services/user.service.ts
> +  private url = environment.apiURL + "/users";
плохая конкатенация, лучше 
```
`${environment.apiURL}/users`
```

2023-07-31 09:20 UTC, Chevich123 requested changes
Присоединюсь к Борису

2023-07-31 09:32 UTC, jeka0 requested changes

2023-07-31 09:32 UTC, jeka0 commented on src/app/pages/products/add/add.component.html
> +        <img style="width: 30vh;" [src]="preview" alt="Product Image" />
Поставь еще ограничение по высоте

2023-07-31 09:32 UTC, jeka0 commented on src/app/pages/products/editing/editing.component.html
> +        <img style="width: 30vh;" [src]="preview" alt="Product Image" />
аналогично

2023-07-31 12:36 UTC, scriptSQD requested changes

2023-07-31 12:36 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +      <div class="drop-zone" [ngClass]="{zonesmaller: preview}" (dragover)="$event.preventDefault()" (drop)="onDrop($event)">
названия классов - это строки, а у тебя получается переменная, и ее нигде нету в коле

2023-07-31 12:36 UTC, scriptSQD commented on src/app/pages/products/editing/editing.component.ts
> +        } else { return of(undefined); }
это можно упростить до return product.image ? imagePreview(...) : of(undefined)

2023-07-31 12:36 UTC, scriptSQD commented on src/app/pages/products/editing/editing.component.ts
> +      switchMap((result: any) => {
any - нехорошо, недо узнать возвращаемый тип и подставить сюда, зачем нам ts?

2023-07-31 14:33 UTC, jeka0 approved these changes

2023-07-31 21:07 UTC, scriptSQD approved these changes

2023-08-01 14:21 UTC, Chevich123 approved these changes

2023-08-01 14:47 UTC, merged