scroll for table, wrap for edit and add pages
Chevich123/learn-fe pull request #24
Opened 2023-08-01 09:01 UTC by AlexandrYurkevich

2023-08-01 13:06 UTC, jeka0 approved these changes

2023-08-01 13:13 UTC, scriptSQD commented on src/app/pages/products/add/add.component.scss
> +.detached-container {
а что это за класс? зачем он нам?

2023-08-01 13:21 UTC, AlexandrYurkevich commented on src/app/pages/products/add/add.component.scss
> +.detached-container {
он всегда был, в диве были контейнер для картинки и контейнер для полей. Сейчас я ему flex-wrap добавил, ибо по другому на чистом css не знаю как по адекватному сделать
  div class="detached-container" style="display: flex"
    div class="field-container"
      ...
просто раньше я флекс в style кинул, а не в класс.

2023-08-01 13:39 UTC, scriptSQD commented on src/app/pages/products/add/add.component.scss
> +.detached-container {
хорошо, тогда есть смысл вынести этот стиль в глобальные - в styles.scss, может другие ребята тоже возьмут на заметку, а то получается, что у тебя 5 строк кода повторяются в двух файлах

2023-08-01 14:29 UTC, Chevich123 approved these changes

2023-08-01 14:29 UTC, Chevich123 commented on src/app/pages/products/products.component.html
> +  <div class="table-container">
Что-то у тебя получился <table> на том же уровне как и .table-container
Надо чтоб <table> был внутри

2023-08-02 05:52 UTC, scriptSQD requested changes
тогда надо зарефакторить класс, чтобы не повторялся

2023-08-02 08:43 UTC, scriptSQD approved these changes

2023-08-02 08:46 UTC, merged