Title
Chevich123/learn-fe pull request #25
Opened 2022-12-16 13:27 UTC by HEKTOOTKEH

2022-12-16 14:16 UTC, scriptSQD requested changes

2022-12-16 14:16 UTC, scriptSQD commented on src/app/app-routing.module.ts
> +        title: 'Workshop - Main menu',
вот как раз TitleStrategy нужен для того, чтобы не писать `Workshop - ...` для каждого роута, а просто указать базовый тайтл, а префикс `Workshop - ` будет добавлять стратегия тайтлов

2022-12-16 14:58 UTC, scriptSQD requested changes

2022-12-16 14:58 UTC, scriptSQD commented on src/app/app-routing.module.ts
> +}
Это все я бы в отдельный файл вынес, и назвал бы как-то более релевантно, типа WorkshopTitleStrategy

2022-12-16 15:55 UTC, jeka0 approved these changes

2022-12-17 09:26 UTC, scriptSQD approved these changes

2022-12-17 14:21 UTC, merged