photo in users
Chevich123/learn-fe pull request #25
Opened 2023-08-01 12:30 UTC by Bleckfi

2023-08-01 13:36 UTC, jeka0 requested changes

2023-08-01 13:36 UTC, jeka0 commented on src/app/pages/users/edit-user/edit-user.component.ts
>    }
У тебя в ngOnInit() повторно идет запрос на пользователя

2023-08-01 14:36 UTC, Chevich123 requested changes

2023-08-01 14:36 UTC, Chevich123 commented on src/app/pages/users/edit-user/edit-user.component.html
> +      <mat-icon style="font-size: 15vh; width: fit-content; height: fit-content"
in-line стили - признак плохой программы. Надо их выкинуть в файл стилей

2023-08-01 14:36 UTC, Chevich123 commented on src/app/services/user.service.ts
> +    return this.http.get<{ data: IUser[]; total: number }>(`${this.url}/users`);
Почему бы не сделать сразу чтоб в this.url была связка с /users?
В этом сервисе же нет работы с другими путями на сервере

2023-08-02 06:15 UTC, scriptSQD approved these changes

2023-08-02 06:15 UTC, scriptSQD commented on src/app/pages/users/edit-user/edit-user.component.ts
> +  onFileSelected(event: any) {
any конечно лучше бы поменять на Event, но с другой стороны оно не дает нам чего-то сильно лучше, чем есть сейчас, ведь у EventTarget только два метода согласно типам - addEventListener/dispatcher, а все остальное - эдж кейсы, так что мы не много выигрываем

2023-08-02 08:50 UTC, jeka0 approved these changes

2023-08-02 14:47 UTC, Chevich123 approved these changes

2023-08-02 17:06 UTC, merged