product pagination changed
Chevich123/learn-fe pull request #26
Opened 2023-08-01 13:25 UTC by DmitryChevich

2023-08-01 14:25 UTC, jeka0 requested changes

2023-08-01 14:25 UTC, jeka0 commented on src/app/services/products.service.ts
> +    return this.http.get<IPaginatedResponse<Product[]>>(`${this.url}/products`);
Параметры сформировал, но добавить в запрос забыл

2023-08-01 14:25 UTC, jeka0 commented on src/app/pages/products/products.component.ts
> +        tap((data) => (this.length = data.total)),
это можно сделать в map, который у нас уже есть

2023-08-01 14:25 UTC, jeka0 commented on src/app/pages/products/products.component.html
>    >
На данный момент переменная length ничего не делает. Можно убрать this.dataSource.paginator и добить сюда [length]="length"

2023-08-01 14:37 UTC, Chevich123 commented on src/app/services/products.service.ts
> +    return this.http.get<IPaginatedResponse<Product[]>>(`${this.url}/products`);
И даже непонятно как тестировалось

2023-08-01 14:38 UTC, Chevich123 commented on src/app/pages/products/products.component.ts
> +        tap((data) => (this.length = data.total)),
tap норм. У нас тут даже получается какой-то single responsibility из SOLID

2023-08-02 06:27 UTC, scriptSQD approved these changes

2023-08-02 06:27 UTC, scriptSQD commented on src/app/services/products.service.ts
> +  private readonly url = environment.apiURL;
тут уже кто-то у нас это фиксил, поэтому при мердже будут конфликты

2023-08-02 06:30 UTC, scriptSQD commented on src/app/services/products.service.ts
> +  private readonly url = environment.apiURL;
только заметил, что вообще тут ты сломал весь сервис, если раньше у нас была ссылка apiUrl/products, и методы опирались на нее, то теперь ты оставил только apiUrl, и методы delete, getById и patch - не работают

2023-08-02 06:31 UTC, scriptSQD requested changes
надо поправить products service

2023-08-05 06:10 UTC, scriptSQD approved these changes
надо было базовую ссылку поправить, но ладно

2023-08-06 06:32 UTC, Chevich123 approved these changes

2023-08-06 06:53 UTC, jeka0 approved these changes

2023-09-02 08:48 UTC, merged