погинация
Chevich123/learn-fe pull request #27
Opened 2022-12-19 15:29 UTC by HEKTOOTKEH

attempt to погинации

2022-12-19 15:31 UTC, HEKTOOTKEH commented
то как было в примере

2022-12-19 16:13 UTC, Chevich123 commented
> attempt to погинации

Похоже на албанский :)

2022-12-19 16:17 UTC, Chevich123 requested changes

2022-12-19 16:17 UTC, Chevich123 commented on src/app/products/products.component.ts
> +        this.products = products;
Попробуй тут 
this.dataSource.data = products;

2022-12-19 16:19 UTC, Chevich123 commented
Отображение я поправил (смотри коммент), но надо чтоб пагинатор управлял запросами. Сейчас забирается сразу все и по этому пагинируется. Немного не то что надо

2022-12-19 20:03 UTC, HEKTOOTKEH commented on src/app/products/products.component.ts
> +        this.products = products;
Спасибо сработало

2022-12-21 14:57 UTC, Chevich123 requested changes

2022-12-21 14:57 UTC, Chevich123 commented on src/app/products/products.component.html
> +    [pageSize]="5"
Это не надою Он возьмет первый из списка опций.
А вот что надо - это ввести новую переменную length
[length]="length"
И в нее присвоить total из ответа с пагинацией

2022-12-21 14:57 UTC, Chevich123 commented on src/app/products/products.component.ts
> +  @ViewChild(MatPaginator, { static: true }) paginator!: MatPaginator;
Это уже не нужно. Нам не нужна связь пагинатора с таблицей. В таблице будет отображаться все что пришло. А пагинатор будет решать что запросить

2022-12-21 14:57 UTC, Chevich123 commented on src/app/products/products.component.ts
> +    this.getProducts();
Это не надо. У тебя получаются два подряд запроса

2022-12-21 14:57 UTC, Chevich123 commented on src/app/products/products.component.ts
> +    this.dataSource.paginator = this.paginator;
Это тоже не надо.

2022-12-21 14:57 UTC, Chevich123 commented on src/app/shared/services/products.service.ts
> +      .set('start', start * limit)
Это отлично

2022-12-21 14:57 UTC, Chevich123 commented on src/app/products/products.component.ts
> +        this.products = products;
Вот тут размести 
this.length = products.total
и подключи к табличке наш массив data
this.dataSource.data = products;

2022-12-21 14:59 UTC, scriptSQD commented on src/app/shared/services/products.service.ts
> +      .set('start', start * limit)
Потому что об этом кто-то подумал заранее =)

2022-12-21 15:54 UTC, Chevich123 requested changes

2022-12-21 15:54 UTC, Chevich123 commented on src/app/products/products.component.html
> +    [length]="lenght"
lenght --- тут тайпо. Должно быть length

2022-12-21 15:54 UTC, Chevich123 commented on src/app/products/products.component.ts
> +import { Component, OnInit, ViewChild } from '@angular/core';
ViewChild & MatPaginator - не нужны

2022-12-21 15:54 UTC, Chevich123 commented on src/app/products/products.component.ts
>    products: IProduct[] = [];
Тебе по сути products не надо. Для инициализации dataSource можно просто использовать типизированный пустой массив. Смотри ниже

2022-12-21 15:54 UTC, Chevich123 commented on src/app/products/products.component.ts
> +  dataSource = new MatTableDataSource(this.products);
> dataSource = new MatTableDataSource([] as IProduct[]);

Инициализируй dataSource с пустым массивом. Просто укажи тип массива

2022-12-21 15:54 UTC, Chevich123 commented on src/app/products/products.component.ts
> +    this.currentpageSize = event.pageSize;
wrong camelCase. Должно быть currentPageSize

2022-12-21 15:54 UTC, Chevich123 commented on src/app/products/products.component.ts
> +  currentpageSize!: number;
Мысль хорошая сохранить текущую пагинацию для рефреша после удаления. Но надо тогда и сделать начальные параметры как на первом запросе. 0 и 5

2022-12-22 08:56 UTC, Chevich123 approved these changes

2022-12-22 10:49 UTC, jeka0 approved these changes

2022-12-22 14:14 UTC, merged