*Added paginator for users table
Chevich123/learn-fe pull request #28
Opened 2022-12-20 15:23 UTC by frynn

2022-12-20 17:46 UTC, HEKTOOTKEH approved these changes

2022-12-21 16:07 UTC, Chevich123 requested changes

2022-12-21 16:07 UTC, Chevich123 commented on src/app/users/users.component.html
> +  [pageSize]="5"
Это не надо. Он сам должен взять первый элемент массива опций. 
Но надо прокинуть length всех записей чтоб правильно возвращалась пагинация. Это поле total в респонзе getUsers

2022-12-21 16:07 UTC, Chevich123 commented on src/app/users/users.component.ts
> +  @ViewChild(MatPaginator, { static: true }) paginator!: MatPaginator;
От пагинатора в ts можешь избавляться. Нам он нужен только как переключалка. Для этого не надо его связывать с таблицей

2022-12-21 16:07 UTC, Chevich123 commented on src/app/users/users.component.ts
> +  dataSource = new MatTableDataSource(this.users);
Так же как и в продуктах - начальную инициализацию можно сделать типизированным пустым массивом
[] as IUser[] 
И тогда users будет не нужен

2022-12-21 16:07 UTC, Chevich123 commented on src/app/users/users.component.ts
> +        this.dataSource.data = users;
Тут надо учесть новый ответ с данными пагинации

2022-12-21 16:07 UTC, Chevich123 commented on src/app/users/users.component.ts
> +    this.dataSource.paginator = this.paginator;
Это не нужно уже

2022-12-22 10:54 UTC, jeka0 approved these changes

2022-12-23 14:24 UTC, Chevich123 approved these changes

2022-12-23 14:24 UTC, merged

2022-12-23 14:24 UTC, scriptSQD approved these changes