get user by token/dashboard
Chevich123/learn-fe pull request #3
Opened 2022-02-04 09:19 UTC by ArtemKomarec

feat: add input styles
feat: add get user profile by token

2022-02-04 15:13 UTC, NikitaFalkon commented on src/app/app.component.ts
> +        console.log('>>', e);
Мне сказали , что ввод в консоль лучше всего вообще убирать, потому-что тогда она засоряется)

2022-02-04 15:13 UTC, NikitaFalkon commented on src/app/app.component.ts
> +      }, (e) => {
Лучше не называть переменные одной буквой, а давать им полные названия

2022-02-04 15:13 UTC, NikitaFalkon commented on src/app/app.component.ts
> +import { Component } from '@angular/core';
У тебя в разных файлах по-разному написаны импорты (где-то с пробелами, а где-то без), не знаю, насколько это критично, но мне кажется, лучше исправить

2022-02-04 17:53 UTC, Chevich123 commented on package.json
> +    "@angular/cdk": "^13.2.1",
А вот это важное замечание. 
Нельзя просто так делать npm i. 
npm i пытается обновить все node_modules и тогда программист сделавний это отвечает что весь код работает идеально и ничего не сломалось.
Если вы опытный программмист и отвечаете за то что сделали, все выверили то тогда вы можете такое делать.
Но джуну или трайни лучше воздержаться от таких действий
Правильно делать npm ci
npm ci не обновляет пакеты а только закачивает именно то что указано в package.json & package-lock.json

2022-02-04 17:53 UTC, Chevich123 commented on package.json
> +    "@angular/cdk": "^13.2.1",
Думаю что пока можно это оставить как есть, но на будущее имейте в виду какие последствия это может привнести

2022-02-04 17:55 UTC, Chevich123 commented on src/app/app.component.ts
> +      }, (e) => {
В случае с error применение буквы e вполне нормальная практика. Но вцелом ты прав

2022-02-04 17:56 UTC, Chevich123 commented
И очень смущает что часть файлов удалена.. Подозреваю что удалено то что сделано Никитой. Это не айс. Надо разбираться

2022-02-04 17:57 UTC, Chevich123 requested changes
Надо разобраться с удаленными файлами. Если это файлы от Никты, то они должны остаться

2022-02-06 19:47 UTC, Martiniks approved these changes

2022-02-07 16:08 UTC, closed without merging