added wrapper, changed routing
Chevich123/learn-fe pull request #3
Opened 2023-07-04 08:42 UTC by AlexandrYurkevich

2023-07-04 09:29 UTC, Chevich123 requested changes

2023-07-04 09:29 UTC, Chevich123 commented on src/app/app.component.scss
> +
Можешь смело это все удалять.

2023-07-04 09:29 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.html
> +<div class="body">
Ну тут тот же вопрос как и к Сергею. Почему не используем готовые штуки из Материал Дизайна с уже прописанными стилями?

2023-07-04 09:29 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.scss
> +.header {
Тут слишком много стилей. Лучше все ж посмотри Материал Дизайн и возьми оттуда кнопки, панельку и что еще захочешь

2023-07-04 09:31 UTC, scriptSQD requested changes

2023-07-04 09:31 UTC, scriptSQD commented on src/app/app-routing.module.ts
> +  { path: 'login', component: LoginComponent },
логин тоже должен быть под враппером, иначе навбар пропадет при переходе на логин

2023-07-04 10:09 UTC, jeka0 approved these changes

2023-07-04 10:31 UTC, jeka0 commented on src/app/app-routing.module.ts
> +  { path: 'login', component: LoginComponent },
Ну, на сколько я понял так и должно быть. Мы можем попасть на основной экран только после авторизации, а без авторизации у нас доступа никуда не будет, следовательно, и навбар не нужен

2023-07-05 13:21 UTC, Chevich123 approved these changes

2023-07-05 13:21 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.html
> +  <a routerLink="/login" *ngIf="router.url !== '/login'">
Бизнеслогика в темплейте не очень хорошо. Я бы посоветовал выкидывать ее в какой геттер
```
   get loginVisible(): boolean {
       this.router.url !== '/login'
   }
```   
Тогда и роутер будет не паблик, а приват, и никаких вычислений в темплейте. Только отображение
Но т.к. тут и так не много бизнеслогики то на данный момент пойдет и такой подход. Просто мысль на будущее

2023-07-05 15:07 UTC, scriptSQD approved these changes

2023-07-05 15:46 UTC, jeka0 approved these changes

2023-07-05 17:44 UTC, merged