вёрстка под мобилки
Chevich123/learn-fe pull request #30
Opened 2022-12-25 09:36 UTC by HEKTOOTKEH

вёрстка под мобилки

2022-12-25 13:31 UTC, frynn requested changes

2022-12-25 13:31 UTC, frynn commented on src/app/wrapper/wrapper.component.html
>    </div>
а где флекс....

2022-12-25 13:31 UTC, frynn commented on src/app/wrapper/wrapper.component.scss
> +  height: 10px;
?

2022-12-25 13:31 UTC, frynn commented on src/app/wrapper/wrapper.component.scss
>  }
флоуты... их кто-то юзает?

2022-12-25 13:32 UTC, scriptSQD requested changes
это + комментарии сергея

2022-12-25 13:32 UTC, scriptSQD commented on src/app/wrapper/wrapper.component.ts
> +  windowWidth = window.innerWidth;
тут тебе надо бы настроить ивент листенер

2022-12-26 09:17 UTC, Chevich123 commented
Мы еще говорили о двух пагинаторах - сверху и снизу.
Флоуты лучше всего убрать совсем. Перейти на флексы.
Ну и было бы интересно чтоб ты на каком-нить брейкпойнте убрал например одну колонку. А так - не интересно получилось

2022-12-26 09:22 UTC, Chevich123 commented
И название ветки по русски - режет глаз. Но тут уж ничего не поменяешь - ПР создан - больше просто так не делай..
Ветки в гите традиционно делают в snake или kebab case на английском языке
https://betterprogramming.pub/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841
Еще как префикс добавляют тему - 
feature : разработка
bugfix: фикс багов
setup: параметры конфигурации

feature/responsive-design

2022-12-26 10:32 UTC, scriptSQD requested changes

2022-12-26 10:32 UTC, scriptSQD commented on src/app/wrapper/wrapper.component.ts
> +  }, 1000);
ерунда абсолютная, тебе нужен BreakpointObserver. Ты работаешь с ангуларом и должен использовать его API для решения своих вопросов, а так ты каждую секунду будешь лишний раз запускать какой-то левый метод и что-то там пересчитывать, несмотря на то, что размер экрана вряд ли поменяется

2022-12-26 14:26 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.ts
> +  }, 1000);
https://material.angular.io/cdk/layout/overview
Тут есть примеры как определять брекпойнты
Можно и сделать по аналогии

2022-12-26 14:27 UTC, Chevich123 commented on src/app/wrapper/wrapper.component.ts
> +  }, 1000);
Ага. Вижу туда и глянул

2022-12-26 14:35 UTC, Chevich123 requested changes

2022-12-26 14:35 UTC, Chevich123 commented on src/app/products/products.component.html
> +        this.currentScreenSize == 'XLarge' || this.currentScreenSize == 'Large'
Не используй == это моветон. Засмеют же
Используй ===

2022-12-26 14:35 UTC, Chevich123 commented on src/app/products/products.component.html
> +        this.currentScreenSize == 'XLarge' || this.currentScreenSize == 'Large'
Это тоже так себе выглядит
А если будет три/пять условий?
['XLarge', 'Large'].includes(this.currentScreenSize)
А лучше бы не пересчитывать тут каждый раз а завести какую константу в компоненте и смотреть на нее.. Одну, две или три - как получится

2022-12-26 14:35 UTC, Chevich123 commented on src/app/products/products.component.html
> +        this.currentScreenSize == 'XLarge' || this.currentScreenSize == 'Large'
А может проще проверить есть ли поле в списке displayedColumns?
displayedColumns.includes('weight');

2022-12-26 14:37 UTC, scriptSQD commented
И вообще здесь можно обойтись без `ngIf`-ов, убрать полностью "маппинг" брэйкпоинтов к каким-то названиям "размеров экрана" и вместо огромных свитч-стэйтментов постепенно добавлять в массив колонки, которые должны отображаться

2022-12-26 14:37 UTC, scriptSQD commented
можно сильно упростить и сократить код, потому что сейчас это конечно сущий ужас

2022-12-26 15:49 UTC, scriptSQD requested changes

2022-12-26 15:49 UTC, scriptSQD commented on src/app/products/products.component.ts
> +  }
этот хук надо удалить

2022-12-26 16:26 UTC, Chevich123 requested changes

2022-12-26 16:26 UTC, Chevich123 commented on src/app/products/products.component.html
> +    <ng-container matColumnDef="wight">
width?

2022-12-26 16:26 UTC, Chevich123 commented on src/app/products/products.component.html
> +    <ng-container matColumnDef="wight">
Тут вообще что-то отображается?

2022-12-27 07:30 UTC, scriptSQD commented on src/app/products/products.component.html
> +    <ng-container matColumnDef="wight">
нет

2022-12-27 13:04 UTC, Chevich123 requested changes

2022-12-27 13:04 UTC, Chevich123 commented on src/app/products/products.component.ts
> +  displayNameMap = [Breakpoints.Small, Breakpoints.Medium, Breakpoints.Large];
Надо еще слушать XLarge. И в switch работать с ним так же как и с Large. Иначе на разрешении 1920 пропадают поля. А они должны быть видны

2022-12-28 12:15 UTC, Chevich123 requested changes

2022-12-28 12:15 UTC, Chevich123 commented on src/app/products/products.component.ts
> +          default: {
Давай тут еще упростим:
```case Breakpoints.Large:
          case Breakpoints.XLarge:
          default: {
            this.displayedColumns.push(
              'width',
              'height',
              'depth',
              'image',
              'country_of_origin',
            );
            break;
          }

2022-12-28 12:16 UTC, Chevich123 commented on src/app/products/products.component.ts
> +          default: {
Объедини одинаковые кейсы в один

2022-12-28 14:01 UTC, jeka0 approved these changes

2022-12-28 14:10 UTC, scriptSQD approved these changes

2022-12-28 14:12 UTC, Chevich123 approved these changes

2022-12-28 14:29 UTC, frynn approved these changes

2022-12-28 14:30 UTC, merged