*Added user avatar display
Chevich123/learn-fe pull request #31
Opened 2022-12-25 13:06 UTC by frynn

2022-12-25 13:35 UTC, scriptSQD approved these changes

2022-12-26 09:30 UTC, Chevich123 requested changes
![image](https://user-images.githubusercontent.com/18614201/209532042-771bc33f-9f88-4170-a8fb-0e22c4c46369.png)
Тут как-то скучено получилось. А в остальном норм

2022-12-26 11:18 UTC, jeka0 approved these changes

2022-12-26 14:23 UTC, Chevich123 approved these changes

2022-12-26 14:23 UTC, merged