*Added ability to change image
Chevich123/learn-fe pull request #34
Opened 2022-12-27 15:42 UTC by frynn

2022-12-27 16:42 UTC, Chevich123 requested changes

2022-12-27 16:42 UTC, Chevich123 commented on src/app/users/edit-user/edit-user.component.html
> +  <img [src]="user.imagePreview" class="avatar" />
![image](https://user-images.githubusercontent.com/18614201/209695590-4e04ec3b-b55a-4bbe-8ab5-c1487330f9a2.png)
Смотрится так себе когда нет картинки. Надо либо что-то дефолтное подсунуть либо убрать вообще

2022-12-28 10:02 UTC, scriptSQD requested changes

2022-12-28 12:11 UTC, Chevich123 approved these changes

2022-12-28 13:59 UTC, jeka0 approved these changes

2022-12-28 14:09 UTC, HEKTOOTKEH approved these changes

2022-12-28 15:12 UTC, scriptSQD approved these changes

2022-12-28 15:12 UTC, merged