Feature/login with material
Chevich123/learn-fe pull request #4
Opened 2022-02-04 13:06 UTC by NikitaFalkon

2022-02-04 13:38 UTC, Martiniks requested changes

2022-02-04 13:38 UTC, Martiniks commented on src/app/login/login.component.html
> +      <button mat-raised-button color="primary" class="addButton" (click)="login()">Log in</button>
В названии классов CSS старайся не использовать камэлстиль. разделять - либо --  либо __

2022-02-04 13:38 UTC, Martiniks commented on src/app/login/login.component.scss
> +.addButton {
Между классами желательно оставлять один пробел.  ps: ctrl+alt+L не вставил пробелы?

2022-02-07 15:57 UTC, Chevich123 approved these changes

2022-02-07 16:16 UTC, merged