Login
Chevich123/learn-fe pull request #4
Opened 2022-11-26 11:40 UTC by jeka0

2022-11-26 11:47 UTC, scriptSQD requested changes
В целом неплохо, но можно чуть доработать

2022-11-26 11:47 UTC, scriptSQD commented on package.json
> +    "angular": "^1.8.3",
Старый AngularJS, откуда он тут вообще?

2022-11-26 11:47 UTC, scriptSQD commented on src/app/dashboard/dashboard.component.ts
> +    this.router.navigateByUrl('/login');
После логаута не обязательно переносить нас на логин, т.к. dashboard публичный и доступен даже незалогиненым пользователям

2022-11-26 11:47 UTC, scriptSQD commented on src/app/login/login.component.html
> +      </button>
Вместо ручного чека в методе login:
https://github.com/Chevich123/learn-fe/blob/81c33103a3c9ddb4770ea680ab1c22df9a8e8c7a/src/app/login/login.component.ts#L31-L33

Можно добавить кнопке проп:
```suggestion
      <button [disabled]="formGroup.invalid" mat-button class="mat-Button" color="custom" (click)="login()">
        Login
      </button>
```

тогда по хорошему надо дописать стиль `.mat-Button:disabled`, чтобы было визуально понятно, что кнопка некликабельна

2022-11-26 11:47 UTC, scriptSQD commented on src/app/login/login.component.ts
> +    }
Прокомментировал выше

2022-11-26 13:54 UTC, scriptSQD approved these changes
Legit!

2022-11-28 10:16 UTC, Chevich123 requested changes

2022-11-28 10:16 UTC, Chevich123 commented on package.json
> -}
Вот такой значек тут не зря. Он означает что в конце файла должна быть пустая строка. Просто нажми ввод в конце файла и коммитни.

2022-11-28 10:16 UTC, Chevich123 commented on src/app/login/login.component.html
> +<div class="Login-background">
Имена классов и id должны быть в snake-case. Переименуй в login-background и проверь остальные классы

2022-11-28 10:18 UTC, Chevich123 commented on src/app/dashboard/dashboard.component.ts
> +    this.router.navigateByUrl('/login');
Впоследствии мы сделаем редирект. Но пока он не нужен.

2022-11-28 11:09 UTC, HEKTOOTKEH approved these changes

2022-11-28 12:00 UTC, Chevich123 approved these changes

2022-11-28 12:40 UTC, scriptSQD approved these changes

2022-11-28 13:28 UTC, frynn approved these changes

2022-11-28 14:13 UTC, merged