Added auth interceptor
Chevich123/learn-fe pull request #5
Opened 2022-11-28 16:03 UTC by frynn

Auth interceptor appends authorization header to each request if access token is present

2022-11-28 16:41 UTC, Chevich123 requested changes

2022-11-28 16:41 UTC, Chevich123 commented on src/app/shared/services/auth.service.ts
>      if (!this.access_token) {
Думаю это тоже можно выкинуть теперь. Мы тут access_token перестали использовать уже. Пусть это будет на совести другой логики

2022-11-29 14:27 UTC, scriptSQD approved these changes

2022-11-29 14:53 UTC, jeka0 approved these changes

2022-11-29 14:55 UTC, Chevich123 approved these changes

2022-11-29 15:05 UTC, HEKTOOTKEH approved these changes

2022-11-29 15:17 UTC, merged