Feature/users
Chevich123/learn-fe pull request #6
Opened 2023-07-07 08:58 UTC by Bleckfi

2023-07-07 11:45 UTC, jeka0 commented on src/app/pages/users/user.ts
> +  phone: string;
Данные о пользователях полученные с сервера имеют поля: email, phone, site, userId, username

2023-07-07 11:45 UTC, jeka0 commented on src/app/auth.service.ts
> +  getUsers(): Observable<any[]> {
C сервера мы получаем не просто массив пользователей, а объект вида {data:User[], total: number}

2023-07-07 11:45 UTC, jeka0 commented on src/app/pages/users/users.component.ts
> +  //       this.users = usersResponse
Чтобы обновить данные таблицы нужно в this.dataSource.data присвоить новые данные, в нашем случае это usersResponse.data

2023-07-10 15:03 UTC, scriptSQD commented on src/app/app-routing.module.ts
>    // { path: 'login', component: LoginComponent },
Коммент уже можно почистить

2023-07-10 15:03 UTC, scriptSQD commented on src/app/auth.service.ts
> +  getUsers(): Observable<any[]> {
+1

2023-07-10 15:03 UTC, scriptSQD commented on src/app/auth.service.ts
> +    return this.http.get<any[]>('http://localhost:3000/users', { headers });
здесь тоже нужно будет поменять тип дженерика

2023-07-10 15:03 UTC, scriptSQD commented on src/app/pages/users/user.ts
> +  phone: string;
+1

2023-07-10 15:03 UTC, scriptSQD commented on src/app/pages/users/users.component.html
здесь тоже нужно будет поменять колонки таблицы на основе нового интерфейса User, который ты должен взять с бэка

2023-07-10 15:04 UTC, scriptSQD approved these changes

2023-07-10 15:04 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +  //   );}
Коммент можно убрать

2023-07-10 15:27 UTC, jeka0 approved these changes

2023-07-10 15:27 UTC, jeka0 commented on src/app/pages/users/user.ts
> +  phone: string;
этот файл уже можно удалить

2023-07-11 14:12 UTC, Chevich123 requested changes
Надо еще с дашборда сделать переход на /users

2023-07-11 14:12 UTC, Chevich123 commented on src/app/auth.service.ts
> +  getUsers(): Observable<{ data: User[]; total: number }> {
Лучше для этого свой сервис создать. UserService

2023-07-11 14:12 UTC, Chevich123 commented on src/app/pages/users/user.ts
> +  phone: string;
Не надо его удалять. Надо оставить как интерфейс и на него завязывать все переменные
Только я бы сделал ```export interface IUser```

2023-07-11 14:12 UTC, Chevich123 commented on src/app/pages/users/users.component.ts
> +  users: User[] = [
Это думаю будет не нужно так как будет браться с сервера

2023-07-11 17:29 UTC, scriptSQD requested changes

2023-07-11 17:29 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +  }
это уде неактуально, у нас есть интерцептор

2023-07-11 17:29 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +        console.log('Users:', this.users);
логи убираем

2023-07-11 17:29 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +    this.loginAndFetchUsers();
вот тут getUsers()

2023-07-11 17:29 UTC, scriptSQD commented on src/app/user-service.service.ts
> +export class UserServiceService {
UserServiceService?... переименуем

2023-07-11 17:29 UTC, scriptSQD commented on src/app/user-service.service.ts
> +    );
снова про интерцептор забыли

2023-07-11 17:29 UTC, scriptSQD commented on src/app/user-service.service.ts
> +  constructor(private auth: AuthService, private http: HttpClient) {}
AuthService нам тут не нужен

2023-07-11 17:29 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +    this.auth.getUsers().subscribe(
и тут надо использовать UsersService

2023-07-12 11:09 UTC, scriptSQD requested changes

2023-07-12 11:09 UTC, scriptSQD commented on src/app/auth.service.ts
> +import { User } from './shared/interfaces/user';
а зачем нам тут этот импорт?

2023-07-12 11:09 UTC, scriptSQD commented on src/app/pages/users/users.component.ts
> +  users: User[] = [];
это тоже неиспользованная переменная

2023-07-12 11:18 UTC, Chevich123 requested changes

2023-07-12 11:18 UTC, Chevich123 commented on src/app/User.service.spec.ts
> +import { TestBed } from '@angular/core/testing';
Имя файла сделай пожалуйста с маленькой буквы
Правила тут такие:
Именования файлов - kebabCase
Типы, интерфейсы и классы - camelCase
Переменные - snakeCase
css классы и идентификаторы - kebabCase

2023-07-12 14:34 UTC, scriptSQD requested changes

2023-07-12 14:34 UTC, scriptSQD commented on src/app/app.module.ts
> +import { MatTableModule } from '@angular/material/table';
Пропустил этот импорт при разрешении конфликтов видимо, ещще один такой же есть чуть выше, из-за этого проект не компилируется (с ошибкой Duplicate identifier 'MatTableModule').

2023-07-12 14:34 UTC, scriptSQD commented on src/app/User.service.spec.ts
тут забыл файлик переименовать

2023-07-12 14:34 UTC, scriptSQD commented on src/app/User.service.ts
тут забыл файлик переименовать

2023-07-13 08:01 UTC, Chevich123 requested changes
И с ветками опять что-то перемудрил..
![image](https://github.com/Chevich123/learn-fe/assets/18614201/0620eaab-2770-4e64-9ca7-dbf4a1697ff4)

2023-07-13 08:01 UTC, Chevich123 commented on src/app/User.service.spec.ts
> +import { TestBed as testBed } from '@angular/core/testing';
Ой не то ты сделал :(
Надо сам файл переименовать и сделать с маленькой буквы. Тут как раз было все верно

2023-07-14 14:56 UTC, Chevich123 approved these changes

2023-07-14 15:36 UTC, scriptSQD approved these changes

2023-07-14 15:42 UTC, merged