Feature/productspage
Chevich123/learn-fe pull request #7
Opened 2023-07-07 12:56 UTC by AlexandrYurkevich

2023-07-07 13:06 UTC, jeka0 approved these changes

2023-07-07 15:54 UTC, Chevich123 requested changes

2023-07-07 15:54 UTC, Chevich123 commented on src/app/pages/products/products.component.ts
> +    this.productsService.getProducts().subscribe({
Этому не место в ngAfterViewInit
В ngAfterViewInit обычно идут вещи которые зависят от @ViewChild or @ViewChildren
Инициализацию dataSource.data перенеси в OnInit
OnInit и служит для получения данных

2023-07-07 15:54 UTC, Chevich123 commented on src/app/product.ts
> +export interface IPaginatedResponse<T> {
Дженерик. Отлично!
НО - это надо поместить в отдельный файл. Например в paginated.ts
И желательно вообще сделать отдельную папку для интерфейсов

2023-07-07 15:54 UTC, Chevich123 commented on src/app/products.service.ts
> +    headers = new HttpHeaders().set("Authorization", `Bearer ${this.auth.token}`)
Это 100% работать не будет если токены не было и он получается через логин.
Лучше сделай это отдельным функцией геттером и дергай каждый раз сервис когда делаешь запрос.
На случай если токен в AuthService уже поменялся!

2023-07-07 16:17 UTC, scriptSQD requested changes

2023-07-07 16:17 UTC, scriptSQD commented on src/app/pages/products/products.component.html
> +        <th mat-header-cell *matHeaderCellDef> Dipth </th>
Чуть-чуть spelling страдает, надо пофиксить

2023-07-07 16:17 UTC, scriptSQD commented on src/app/pages/products/products.component.html
> +        aria-label="Select page of periodic elements">
Арию мы не увидим,но ее услышат слепые, которые пользуются экранными ридерами, чтобы листать сайты. Этот лэйбел надо поменять, чтобы он описывал, что на самом деле делает этот пагинатор (напр. Select page of products table)

2023-07-10 14:59 UTC, scriptSQD requested changes

2023-07-10 14:59 UTC, scriptSQD commented on src/app/pages/products/products.component.ts
> +    this.dataSource.sort = this.sort;
Это тоже можно перенести в OnInit

2023-07-10 14:59 UTC, scriptSQD commented on src/app/pages/products/products.component.ts
> +      next: (products) => {console.log("success"); this.dataSource.data = products.data},
Лог можно убрать если пушим код в продакшн

2023-07-10 15:37 UTC, jeka0 commented on src/app/shared/interfaces/paginated.ts
> +}
Оставляй пустую строку в файлах, чтобы избавится от этого красного знака, так лучше для Git

2023-07-10 15:50 UTC, scriptSQD commented on src/app/shared/interfaces/paginated.ts
> +}
Гиту в общем-то без разницы, а вот операционные системы по-разному определают, что файл закончился. Для Unix-подобных ОС это LF - line feed, тоже самое, что '\n' в коде на языке C. А вот Windows определяет окончание файла по символу CRLF - carriage return line feed или '\r\n' в языке C. На самом деле сейчас ОС умеют работать и с тем, и с тем, а красный кружочек появляется на гитхабе из-за стандартной конфигурации, которая просит гит оставлять окончания файлов как LF.

2023-07-10 15:56 UTC, jeka0 commented on src/app/shared/interfaces/paginated.ts
> +}
я к тому, что при добавлении новых строк в конец файла, на последнюю подставится знак переноса строки, если его там не было, то гит пометит эту строку как измененную, хотя по факту она не менялась

2023-07-11 14:05 UTC, Chevich123 requested changes

2023-07-11 14:05 UTC, Chevich123 commented on src/app/pages/products/products.component.ts
> +      next: (products) => {console.log("success"); this.dataSource.data = products.data},
Только это осталось

2023-07-12 09:34 UTC, scriptSQD approved these changes

2023-07-12 10:20 UTC, Chevich123 requested changes
Отлично передвинул ветку на main.
Хорошо убрал хэдеры.
Остались мелкие придирки.
Теперь после фикса тебе не надо уже танцевть с бубном - достаточно просто пушнуть коммит

2023-07-12 10:20 UTC, Chevich123 commented on src/app/pages/dashboard/dashboard.component.html
> +<a mat-button color="primary" href="/products">Products</a>
Переход по href перегружает страничку целиком. Это неприятно. У нас же Single Page Application.
Правильнее сделать routerLink. Тогда не будет перегрузки странички а просто переход на нужную!

2023-07-12 10:20 UTC, Chevich123 commented on src/app/products.service.ts
> +  constructor(private http: HttpClient, private auth: AuthService) { }
AuthService тут уже не нужен. Его можно удалить

2023-07-12 12:12 UTC, Chevich123 approved these changes

2023-07-12 12:15 UTC, merged