Feature/addproduct
Chevich123/learn-fe pull request #9
Opened 2023-07-13 13:20 UTC by AlexandrYurkevich

2023-07-13 14:56 UTC, jeka0 commented on src/app/pages/products/add/add.component.html
> +    <button mat-raised-button color="primary" type="submit">Add Product</button>
Было бы хорошо еще добавить кнопку для возврата на экран продуктов

2023-07-14 11:03 UTC, Chevich123 requested changes

2023-07-14 11:03 UTC, Chevich123 commented on src/app/pages/products/add/add.component.ts
> +    image: ['', this.positiveNumberValidator],
Ой.. Тут так не надо.. Тут будет строка и неявная. Убери это

2023-07-14 11:03 UTC, Chevich123 commented on src/app/pages/products/add/add.component.ts
> +    return (control.value === '' || control.value > 0) ? null : { positiveNumber: true };
Это можно упростить
```
return control?.value > 0 ? null : { positiveNumber: true };
```

2023-07-14 15:30 UTC, jeka0 approved these changes

2023-07-15 06:42 UTC, Chevich123 approved these changes

2023-07-15 14:55 UTC, scriptSQD requested changes

2023-07-15 14:55 UTC, scriptSQD commented on src/app/pages/products/add/add.component.ts
> +      next: (ret) => this.router.navigateByUrl('/products'),
тут параметр можно просто игнорить

2023-07-15 14:55 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +    <button mat-raised-button color="primary" type="submit">Add Product</button>
я бы сюда добавил [disabled]="productForm.invalid"

2023-07-15 14:55 UTC, scriptSQD commented on src/app/pages/products/add/add.component.ts
> +    this.productForm.valid &&
а тут убрал бы проверку валидности, потому что кнопка ра отправку формы дудет неактивной, если у формы есть ошибки

2023-07-15 14:55 UTC, scriptSQD commented on src/app/pages/products/add/add.component.ts
> +    depth: ['', this.positiveNumberValidator],
это все можно нативно сделать числами, через formBuilder.control<number>(0, validators)

2023-07-15 14:55 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +      <input matInput formControlName="width" placeholder="Width">
а тут добавить type="number"

2023-07-15 14:55 UTC, scriptSQD commented on src/app/pages/products/add/add.component.ts
> +  positiveNumberValidator(control: FormControl) {
здесь будет FormControl<number>

2023-07-15 14:55 UTC, scriptSQD commented on src/app/pages/products/add/add.component.ts
> +    return (control.value === '' || control.value > 0) ? null : { positiveNumber: true };
и тут value будет иметь тип number, тогда можно упростить до {positiveNumber: control.value > 0)

2023-07-17 08:29 UTC, Chevich123 commented on src/app/pages/products/add/add.component.ts
> +    depth: ['', this.positiveNumberValidator],
Ну так тоже норм. И мне кажется так более наглядно и понятно

2023-07-17 11:24 UTC, scriptSQD requested changes

2023-07-17 11:24 UTC, scriptSQD commented on src/app/pages/products/products.component.ts
> +          next: (ret) => this.dataSource.data = this.dataSource.data.filter(el => el._id != productId),
лучше по новой делать фетч данных, вынеси из онИнит getProducts в отдельный медот, и вызывай из онИнит и после успешного удаления

2023-07-18 08:09 UTC, AlexandrYurkevich commented on src/app/pages/products/add/add.component.ts
> +    return (control.value === '' || control.value > 0) ? null : { positiveNumber: true };
Это не работает вообще при всех значениях, валидаторы же возвращают либо налл либо ошибки, упрощать здесь вообще нечего. типо вот Validators.required - export function requiredValidator(control: AbstractControl): ValidationErrors|null {
  return isEmptyInputValue(control.value) ? {'required': true} : null;
}

2023-07-18 08:12 UTC, AlexandrYurkevich commented on src/app/pages/products/add/add.component.ts
> +    return (control.value === '' || control.value > 0) ? null : { positiveNumber: true };
у нас судя по бекендовскому интерфейсу всё кроме имени и производителя опционально, при типе number пустая строка всё ещё просто строка.

2023-07-18 08:29 UTC, scriptSQD requested changes

2023-07-18 08:29 UTC, scriptSQD commented on src/app/pages/products/add/add.component.html
> +      <input matInput formControlName="width" placeholder="Width" type="number">
если уж ты поменял тут type, то в productForm точно надо делать this.fb.control<number | undefined>(undefined, this.isPositiveNumber)

2023-07-18 08:29 UTC, scriptSQD commented on src/index.html
> +  <body class="mat-typography, mat-app-background">
запятая тут лишняя, теряешь класс mat-typography

2023-07-18 11:01 UTC, scriptSQD requested changes
до сих пор не поменял контролы в форме на типизированные под число

2023-07-18 15:14 UTC, Chevich123 commented
> до сих пор не поменял контролы в форме на типизированные под число

Думаю нам в этом курсе это не актуально. Давай обойдемся простыми формКонтроллами

2023-07-18 15:21 UTC, scriptSQD commented
> > до сих пор не поменял контролы в форме на типизированные под число
> 
> Думаю нам в этом курсе это не актуально. Давай обойдемся простыми формКонтроллами

![Screenshot_20230718_182002_GitHub.jpg](https://github.com/Chevich123/learn-fe/assets/73490413/b5741f52-f566-4aa7-a05c-645d46a05f65)

Вот наша практика с зимы, там не было вопросов

2023-07-18 19:05 UTC, Chevich123 commented
Но в таком случае надо переделывать и логин и продукты. Мы сейчас везде не завязывались на типы и интерфейсы. Да и не обязательно это для нашего начального курса. Хотя и полезно и интересно

2023-07-18 19:12 UTC, scriptSQD approved these changes

2023-07-18 19:14 UTC, scriptSQD commented
> Но в таком случае надо переделывать и логин и продукты. Мы сейчас везде не завязывались на типы и интерфейсы. Да и не обязательно это для нашего начального курса. Хотя и полезно и интересно

С логином и юзерами не все так страшно, там и так и так строки будут, просто для юзеров одна из них - с валидацией на телефон, другая - с валидацией на ссылку (сайт); а в логине юзернэйм и пароль - тоже строки, так что в целом там не обязательно, там и так нативные типы совпадают

2023-07-18 19:14 UTC, merged