Feature/create and delete
Chevich123/learn-fe pull request #9
Opened 2022-02-09 15:00 UTC by NikitaFalkon

2022-02-09 15:17 UTC, Chevich123 requested changes
То ты тогда все приведи к тому как тебе будет нравиться, перемести ветку на main и заново запроси ревью.
Нет смысла ревьювать если код изменится

2022-02-11 14:50 UTC, Martiniks approved these changes

2022-02-11 14:50 UTC, Martiniks commented on src/app/app.component.ts
> +  // user: IUser = new IUser('', '');
Старайтесь удалять коменты перед пуллреквестом

2022-02-11 15:52 UTC, Chevich123 commented
![image](https://user-images.githubusercontent.com/18614201/153622145-8628a712-e42c-46a0-9f72-699885512ac5.png)
Тут как-то не по феншую.. Я такого подтверждения еще никогда не видел
Используй диалог материала https://material.angular.io/components/dialog/overview
И сделай что-то типа такого:
![image](https://user-images.githubusercontent.com/18614201/153623731-ed2906df-1972-464f-a896-9ea7033f4c54.png)

2022-02-11 15:53 UTC, Chevich123 requested changes
Смотри комменты

2022-02-16 14:34 UTC, merged